### ISSUE TITLE
Errror in preprocess_data.py

### ISSUE THREAD

**Issue by xiankgx** [zllrunning/face-parsing.PyTorch#10]
`mask[sep_mask == 225] = l`

Shouldn't it be 255?

**Comment by TalentedMUSE** [comment]
@xiankgx The image is converted to PIL mode "P" and the max of the image is 225. You can use numpy.unique() to check it out.

**Comment by xiankgx** [comment]
I see, don't really have much experience with PIL 'P' mode image.

Thanks for your input.
