### ISSUE TITLE
where can I find all label

### ISSUE THREAD

**Issue by zhangqijun** [zllrunning/face-parsing.PyTorch#12]
like 
```
    table = {
        'hair': 17,
        'upper_lip': 12,
        'lower_lip': 13
    }
```
Looks different from celebamask-hq
*   Mask labels are defined as following:

| Label list |  |  |
| --- | --- | --- |
| 0: 'background' | 1: 'skin' | 2: 'nose' |
| 3: 'eye\_g' | 4: 'l\_eye' | 5: 'r\_eye' |
| 6: 'l\_brow' | 7: 'r\_brow' | 8: 'l\_ear' |
| 9: 'r\_ear' | 10: 'mouth' | 11: 'u\_lip' |
| 12: 'l\_lip' | 13: 'hair' | 14: 'hat' |
| 15: 'ear\_r' | 16: 'neck\_l' | 17: 'neck' |
| 18: 'cloth' |  |  |

**Comment by zhangqijun** [comment]
sorry,find it.
            # atts = [1 'skin', 2 'l_brow', 3 'r_brow', 4 'l_eye', 5 'r_eye', 6 'eye_g', 7 'l_ear', 8 'r_ear', 9 'ear_r',
            #         10 'nose', 11 'mouth', 12 'u_lip', 13 'l_lip', 14 'neck', 15 'neck_l', 16 'cloth', 17 'hair', 18 'hat']

**Comment by showkeyjar** [comment]
but I use this order to predict, the result still make me confused
![parsing_face](https://user-images.githubusercontent.com/16154787/136645832-a6f19772-21ee-40e7-ba0f-15458fc3369a.jpg)
:
