### ISSUE TITLE
Key already registered with the same priority: GroupSpatialSoftmax

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [zllrunning/face-parsing.PyTorch#22]
When I am running the code from the following command
```
python test.py
```
Then I am getting just the following output:
**Key already registered with the same priority: GroupSpatialSoftmax**

Please help me.

**Comment by mathmax12** [comment]
Hi @mayanktiwariiiitdmj
Is this solve? I got the same issue.

**Comment by mayanktiwariiiitdmj** [comment]
yes, I solved this issue by deleting the current environment and then making another.
