### ISSUE TITLE
您好！关于网络的准确度是如何的？有训练好的网络可以提供吗？

### ISSUE THREAD

**Issue by wqz960** [zllrunning/face-parsing.PyTorch#3]
感谢您的代码啊！！！
就是您能提供下 您的实验日志那些的吗 准确率什么的？ 还有预训练网络可以提供下吗 手头设备不是太好 非常感谢了！！！

**Comment by zllrunning** [comment]
训练日志没有存，预训练模型可以提供：[](https://drive.google.com/open?id=154JgKpzCPW82qINcVieuPH3fZ2e0P812)

**Comment by zllrunning** [comment]
日志没有存下来，预训练模型在readme文件已经提供，也可以[在这下载](https://drive.google.com/open?id=154JgKpzCPW82qINcVieuPH3fZ2e0P812)
