### ISSUE TITLE
请问如果我使用其他的数据集,至少需要多少张图片

### ISSUE THREAD

**Issue by primejava** [zllrunning/face-parsing.PyTorch#5]
首先很感谢你的项目,效果很高.我想问的是,假设我想对图片中的水果进行分割,那么我至少需要准备多少数据集,可以达到类似的效果呢.一千张以内有可能吗?因为自己动手标注实在太累了.
另外,你训练这个模型花费了多少时间呢

**Comment by austingg** [comment]
@primejava  1000张应该可以做一个不错的启动训练集了。 训练时间要看你的训练机器以及训练集的规模。 多尝试，再慢慢想办法

**Comment by primejava** [comment]
thank you
